template_project/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name = 'relative'),
    path('other/', views.other, name = 'other'),

]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

template_project/basic_app/models.py
from django.db import models

# Create your models here.

template_project/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dic = {'name':'Hello World!', 'number': 100}
    return render(request, 'basic_app/index.html', context_dic)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

template_project/templates/basic_app/index.html
<!DOCTYPE html>
{% load my_extras %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Main</title>
  </head>
  <body>
    <h1>This is the Main Page!</h1>
    <h2>{{ name|cut_word:"Hello" }}</h2>
    <h2> {{ number|add:"99" }} </h2>
  </body>
</html>

template_project/templates/basic_app/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Other</title>
  </head>
  <body>
    <h1>This is the Other Page!</h1>
    <a href="{% url 'basic_app:relative' %}">Click Here to go to the relative page!</a>
    <a href="{% url 'admin:index' %}">link to admin panel</a>
    <a href="{% url 'index' %}">Link to Index</a>
  </body>
</html>

template_project/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative url template</title>
  </head>
  <body>
    <h1>This is the relative URL template Page</h1>
    <a href="{% url 'basic_app:other' %}">Click here to go to other!</a>
  </body>
</html>